#!/bin/bash

set -e

# Run lint on the build
echo -e "\033[33m";
echo "  _    _     _   _           ";
echo " | |  (_)_ _| |_(_)_ _  __ _ ";
echo " | |__| | ' \  _| | ' \/ _\` |";
echo " |____|_|_||_\__|_|_||_\__, |";
echo "                       |___/ ";
echo -e "\033[0m";
eslint src; true

echo -e "\033[32m";
echo "SUCCESS"
echo -e "\033[0m";

echo -e "\033[35m";
echo "No test defined."
echo -e "\033[0m";

echo " "
echo " "
